### ISSUE TITLE
Use the exports better in _setenv_android.bash

### ISSUE THREAD

**Issue by licaon-kter** [smarek/android-unbound-dns#11]
`export _PACKAGENAME_URL` should use exported `_PACKAGE_NAME`

from.
`export _UNBOUND_URL="https://unbound.net/downloads/unbound-1.5.7.tar.gz"`
to
`export _UNBOUND_URL="https://unbound.net/downloads/$_UNBOUND_NAME.tar.gz`

That works for _unbound_ and _openssl_ but needs more formatting for _expat_ and _libevent_

Have any prefered way to do it besides splitting it in NAME and VERSION ?

**Comment by smarek** [comment]
Well since the naming is not always 1:1 mapping, I've resolved to use name and URL in separate manners, so we're not limited to use URLs with non-standard file names. What may be missing is to verify downloaded package `sha1sum`.
I'm closing this issue, because keeping the names this way is handy, when you're trying to upgrade specific dependency (downloaded packages and expanded folder name differs between versions)
